name: Build (helper)

permissions:
  contents: read

on:
  workflow_call:

env:
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_DEV_DEBUG: 0
  CARGO_TERM_COLOR: always
  dummare_BUILDER: github-ci
  RUST_BACKTRACE: 1
  CC: clang
  RUSTFLAGS: "-D warnings"
  RUSTUP_MAX_RETRIES: 10

jobs:
  modern-default:
    # Test modern compilers on standard platforms on Linux.
    name: "${{ matrix.target }} - ${{ matrix.rust }} (default configuration)"
    runs-on: ubuntu-latest
    env:
      CARGO_PROFILE_DEV_DEBUG: 1
      CARGO_PROFILE_DEV_SPLIT_DEBUGINFO: ${{ matrix.debug_info }}
      RUSTFLAGS: -D warnings -Clink-arg=-Wl,--compress-debug-sections=zlib
    strategy:
      fail-fast: false
      matrix:
        target:
          - aarch64-unknown-linux-musl
          - armv7-unknown-linux-musleabihf
          - i686-unknown-linux-musl
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
        rust:
          - stable
          - nightly
        debug_info:
          - packed
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
      - name: Install Rust
        run: rustup install --profile minimal ${{ matrix.rust }} && rustup default ${{ matrix.rust }}
      - name: Print environment info
        run: |
          echo "# Rust"
          rustc -Vv
          echo "# Cargo"
          cargo -Vv
          echo "# GCC"
          gcc -v
          echo "# Clang"
          clang -v
          echo "# Ld"
          ld -v
      - name: Install cross
        uses: taiki-e/install-action@0ed4032d5406d133639ce4e858011eb498223338 # v2.62.39
        with:
          tool: cross@latest
      # TODO: Cache is broken for cross compiles, figure this out
      #- name: Cache builds
      #  uses: Swatinem/rust-cache@v2.7.8
      #  with:
      #    key: ${{ matrix.target }}-${{ matrix.rust }}
      - name: Cross compile binary
        run: cross build --release --locked --target ${{ matrix.target }} --verbose
      - name: Cross compile tests
        run: cross test --release --no-run --locked --target ${{ matrix.target }} --verbose
      - name: Cross test
        run: cross test --release --locked --target ${{ matrix.target }} --verbose
      - name: Compress binary
        if: matrix.rust == 'stable' && contains(matrix.target, 'musl')
        run: |
          mkdir dummare
          cp target/${{ matrix.target }}/release/dummare dummare/
          if [[ -f target/${{ matrix.target }}/release/dummare.dwp ]]; then
            # No split release info for RISCV
            cp target/${{ matrix.target }}/release/dummare.dwp dummare/
          fi
          tar cf dummare.tar dummare
          zstd -T0 -6 dummare.tar
      - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        if: matrix.rust == 'stable' && contains(matrix.target, 'musl')
        with:
          name: dummare_${{ matrix.target }}.tar.zst
          path: dummare.tar.zst
          retention-days: 7
      - name: Clean up temporary items
        run: |
          rm -rf dummare dummare.tar dummare.tar.zst

  configurations:
    # Test non-standard configurations, MSRV and Rust versions
    name: "Test: \"${{ matrix.features }}\" (Linux), Rust ${{ matrix.rust }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        features:
          - --all-features
        rust:
          - 1.92.0
          - stable
          - nightly
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
      - name: Install Rust
        run: rustup install --profile minimal  ${{ matrix.rust }} && rustup default ${{ matrix.rust }}
      - name: Get cargo-binstall
        run: |
          curl -L https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-musl.tgz | tar -zxf - && mv cargo-binstall $HOME/.cargo/bin/
      - name: Cache builds
        uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
      - name: Compile
        run: cargo test --locked ${{ matrix.features }} --verbose --no-run
      - name: Test
        run: cargo test --locked ${{ matrix.features }} --verbose
    env:
      # Warnings are ok for now here due to private APIs that will be public in the future.
      RUSTFLAGS: ""
