name: Release

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:

  dummare:
    name: "Release dummare"
    permissions:
      attestations: write
      contents: write
      id-token: write
    if: github.repository_owner == 'VorpalBlade' && startsWith(github.event.release.name, 'v')
    uses: ./.github/workflows/act_build_release.yml
    with:
      release_name: ${{ github.event.release.name }}
      project: dummare
      archive_prefix: ${{ github.event.release.name }}
      binaries: dummare
    secrets:
      AUR_USERNAME: ${{ secrets.AUR_USERNAME }}
      AUR_EMAIL: ${{ secrets.AUR_EMAIL }}
      AUR_SSH_PRIVATE_KEY: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
